ResturantSystem/Models/Enrollment.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enrollment
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string SecurityAnswer { get; set; }
        public string Gender { get; set; }
    }
}

ResturantSystem/Controllers/EnrollmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ResturantSystem.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace ResturantSystem.Controllers
{
    public class EnrollmentController : Controller
    {
        public string value = "";

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Enroll e)
        {
            if (Request.HttpMethod == "POST")
            {
                Enroll er = new Enroll();
                using (SqlConnection con = new SqlConnection("Data Source=DESKTOP-TKCK2P7\\SQLEXPRESS;Integrated Security=true;Initial Catalog=Resturantsystem"))
                            //public static string constring = @"Data Source=DESKTOP-RBKCL90\SQLEXPRESS;Initial Catalog=ResturantSystem;Integrated Security=True";

                {
                    using (SqlCommand cmd = new SqlCommand("SP_EnrollDetail", con))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@FirstName", e.FirstName);
                        cmd.Parameters.AddWithValue("@LastName", e.LastName);
                        cmd.Parameters.AddWithValue("@UserName", e.UserName);
                        cmd.Parameters.AddWithValue("@Password", e.Password);
                        cmd.Parameters.AddWithValue("@Gender", e.Gender);
                        cmd.Parameters.AddWithValue("@Email", e.Email);
                        cmd.Parameters.AddWithValue("@Phone", e.PhoneNumber);
                        cmd.Parameters.AddWithValue("@SecurityAnwser", e.SecurityAnwser);
                        cmd.Parameters.AddWithValue("@status", "INSERT");
                        con.Open();
                        ViewData["result"] = cmd.ExecuteNonQuery();
                        con.Close();
                    }
                }
            }
            return View();
        }

    }
}

ResturantSystem/Views/Enrollment/Index.cshtml
@model ResturantSystem.Models.Enroll

@{
    ViewBag.Title = "ENROLLMENT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



    <!------ Include the above in your HEAD tag ---------->
    @using (Html.BeginForm("Index", "Enrollment", FormMethod.Post))
    {
        <div class="container register" style="padding-top: 100px">
            <div class="row">
                <div class="col-md-3 register-left">
                    <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt="" />

                </div>
                <div class="col-md-9 register-right">
                    <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" href="@Url.Action("Index","Enrollment/Index")" role="tab" aria-controls="home" aria-selected="true">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="profile-tab" href="@Url.Action("Index","UserLogin")" role="tab" aria-controls="profile" aria-selected="false">Login</a>
                        </li>
                    </ul>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                            <h3 class="register-heading">Register here</h3>
                            <div class="row register-form">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.FirstName, new { @class = "form-control", placeholder = "First Name *" })
                                        @Html.ValidationMessageFor(e => e.FirstName)
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.LastName, new { @class = "form-control", placeholder = "Last Name *" })
                                        @Html.ValidationMessageFor(e => e.LastName)
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.UserName, new { @class = "form-control", placeholder = "User Name *" })
                                        @Html.ValidationMessageFor(e => e.UserName)
                                    </div>
                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.Password, new { id = "password", @class = "form-control", placeholder = "Password *" })
                                        <span id="result"></span>
                                        @Html.ValidationMessageFor(e => e.Password)
                                    </div>
                                    <div class="form-group">
                                        @Html.PasswordFor(e => e.Confirmpwd, new { @class = "form-control", placeholder = "Confirm Password *" })
                                        @Html.ValidationMessageFor(e => e.Confirmpwd)
                                    </div>
                                    <div class="form-group">
                                        <div class="maxl">
                                            @Html.RadioButtonFor(e => e.Gender, "Male", new { @class = "radio inline" })<span> Male </span>
                                            @Html.RadioButtonFor(e => e.Gender, "Female", new { @class = "radio inline" })<span>Female </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.Email, new { @class = "form-control", placeholder = "Your Email *" })
                                        @Html.ValidationMessageFor(e => e.Email)
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.PhoneNumber, new { @class = "form-control", placeholder = "Your Phone *" })
                                        @Html.ValidationMessageFor(e => e.PhoneNumber)

                                    </div>
                                    <div class="form-group">
                                        <select class="form-control">
                                            <option class="hidden" selected disabled>Please select your Sequrity Question</option>
                                            <option>What is your Birthdate?</option>
                                            <option>What is Your old Phone Number</option>
                                            <option>What is your Pet Name?</option>
                                        </select>
                                    </div>
                                    <div class="form-group">
                                        @Html.TextBoxFor(e => e.SecurityAnwser, new { @class = "form-control", placeholder = "`Answer *" })
                                        @Html.ValidationMessageFor(e => e.SecurityAnwser)

                                    </div>
                                    <input type="submit" class="btnRegister" value="Register" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <script type="text/javascript">

             $(function () {
                var msg = '@ViewData["result"]';
                if (msg == '1')
                {
                    alert("User Details Inserted Successfully");
                    window.location.href = "@Url.Action("Index", "Enrollment")";
                 }
                });
            </script>
            }
        </div>
    }
    