ResturantSystem/Models/DiscountTable.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResturantSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountTable
    {
        public int Id { get; set; }
        public string FoodCategory { get; set; }
        public string ProductName { get; set; }
        public string OfferPercent { get; set; }
        public string Detail { get; set; }
    }
}

ResturantSystem/Controllers/Admin/Discount/DiscountController.cs
using ResturantSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ResturantSystem.Controllers.Admin.Discount
{
    public class DiscountController : Controller
    {
        ResturantsystemEntities db;
        // GET: Discount
        public DiscountController()
        {
            db = new ResturantsystemEntities();
        }
        public ActionResult Index()
        {
            var discount = db.DiscountTables.ToList();
            return View(discount);
        }
        public ActionResult AddDiscount()
        {
            var Categories = db.Categories.ToList();
            ViewBag.Categories = new SelectList(Categories, "FoodCategory", "FoodCategory");
            var productTables = db.ProductTables.ToList();
            ViewBag.productTables = new SelectList(productTables, "ProductName", "ProductName");
            return View();

        }

        [HttpPost]
        public ActionResult AddDiscount(DiscountTable recordsave)
        {
            db.DiscountTables.Add(recordsave);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult EditDiscount(int Id)
        {
            var Categories = db.Categories.ToList();
            ViewData["Categories"] = new SelectList(Categories, "FoodCategory", "FoodCategory");
            var productTables = db.ProductTables.ToList();
            ViewData["productTables"] = new SelectList(productTables, "ProductName", "ProductName");
            DiscountTable data = db.DiscountTables.Find(Id);
            return View(data);

        }

        // POST: Admin/Edit/5
        [HttpPost]
        public ActionResult EditDiscountData(DiscountTable update)
        {

            // TODO: Add update logic here

            db.Entry(update).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DeleteDiscount(int Id)
        {
            DiscountTable data = db.DiscountTables.Find(Id);
            return View(data);
        }
        public ActionResult DeleteDiscountData(int Id)
        {
            DiscountTable data = db.DiscountTables.Find(Id);
            db.DiscountTables.Remove(data);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //uta bata yo action call hunxa esma chai hamle FoodCategory anusar product data leko xam 
        public JsonResult GetProductByCategoryId(string FoodCategory)
        {
            List<ProductTable> ProductTable = db.ProductTables.Where(x => x.FoodCategory == FoodCategory).ToList();

            if (ProductTable == null)
            {
                return Json(new
                {
                    Success = false,
                },
                JsonRequestBehavior.AllowGet);
            }
            return Json(ProductTable, JsonRequestBehavior.AllowGet); // esma aako data Json format ma return hunxa
        }
    }
}

ResturantSystem/Views/Discount/AddDiscount.cshtml
@model ResturantSystem.Models.DiscountTable
@{
    ViewBag.Title = "AddDiscount";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .background {
        background-color: white;
    }

    .btn {
        font-weight: 500;
        color: white;
    }

    .card-title {
        font-size: 20px;
        color: white;
    }
</style>
<div class="background">

    <div class="text-right ">
        <a href="@Url.Action("Index","Discount")" type="button" class="btn btn-warning mt-2 mr-3 ">+ Goto List</a>
    </div>
    <div class="card card-warning mt-2">
        <div class="card-header ">
            <h3 class="card-title ml-2">Discount Add</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body ml-3">
            @using (Html.BeginForm("AddDiscount", "Discount", FormMethod.Post))
            {
                <div class="row">
                    <div class="col-sm-6">

                        <!-- text input -->

                        <div class="form-group">
                            <label for="">FoodCategory</label>
                            @Html.DropDownList("Categories", null, "Select Category", htmlAttributes: new { @Name = "FoodCategory", @class = "form-control  mt-1", @id = "Categories" })

                        </div>
                        <div class="form-group">
                            <label for="">Product Name</label>
                            @Html.DropDownList("ProductTables", null, "Select Product Name", htmlAttributes: new { @Name = "ProductName", @class = "form-control  mt-1", @id = "Product" })

                        </div>
                        <div class="form-group">
                            <label for="">Offer Percent</label>
                            <input type="text" name="OfferPercent" class="form-control  mt-1" id="offerpercent" placeholder="Enter Offer Percent">
                        </div>
                        <div class="form-group">
                            <label for="">Detail</label>
                            <input type="text" name="Detail" class="form-control  mt-1" id="detail" placeholder="Enter Detail of Discount">
                        </div>
                        <br />

                        <button type="submit" class="btn btn-warning ml-2" value="Submit">Submit</button>

                    </div>

                </div>

            }
        </div>
        <!-- /.card-body -->
    </div>

</div>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

@*<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="></script>*@

<script>

    //Category ko dropdown bata data change hunai bitikai yo jquery call hunxa normal javascript jasari nai on change ho 
    $(document).on('change', "#Categories", function () {
        var FoodCategory = $(this).find(":selected").val(); //aile select gareko value linxa
        ProductSearch(FoodCategory); //function for product search
    });

    function ProductSearch(FoodCategory) {

        //yo code le euta action call hunxa jun ma chai category pass gareko xa in data 
        $.ajax({
            dataType: 'json',
            data: { FoodCategory: FoodCategory},
            url: "@Url.Action("GetProductByCategoryId","Discount")",  //yo chai hamro kun action call garne vanera ho maile Discount Controller ko  GetProductByCategoryId call gareko xu
            success: function (products) {
                var rData = SetDropDownData(products); //aako data lai euta function ma pass gareko ho 
                $("#Product").html(rData); //final converted data set to Product
            }
        });
    }

    function SetDropDownData(Data) {
        //in this function dropdown ma hune gari option value format ma convert gareko ho
        var Result = '';
        if (Data.length > 0) {
            Result += '<option value="" readonly>--Select Product--</option>';
            for (var i = 0; i < Data.length; i++) {

                if (Data[i] != null) {
                    Result += '<option value="' + Data[i].ProductName + '">' +
                        Data[i].ProductName +
                        '</option>';
                }
            }
            return Result;
        }
        return Result;
    }
</script>

ResturantSystem/Views/Discount/EditDiscount.cshtml
@model ResturantSystem.Models.DiscountTable
@{
    ViewBag.Title = "EditDiscount";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .background {
        background-color: white;
    }

    .btn {
        font-weight: 500;
        color: white;
    }

    .card-title {
        font-size: 20px;
        color: white;
    }
</style>

<div class="background">

    <div class="text-right ">
        <a href="@Url.Action("Index","Discount")" type="button" class="btn btn-warning mt-2 mr-3 ">+ Goto Discount List</a>
    </div>
    <div class="card card-warning mt-2">
        <div class="card-header ">
            <h3 class="card-title ml-2">Update Discount</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body ml-3">
            @using (Html.BeginForm("EditDiscountData", "Discount", FormMethod.Post))
           
            {
            <div class="row">
                <div class="col-sm-6">

                    <!-- text input -->
                    <input type="hidden" name="Id" value="@Model.Id" />
                    <div class="form-group">
                        <label for="">FoodCategory</label>
                        @Html.DropDownListFor(m => m.FoodCategory, ViewData["Categories"] as IEnumerable<SelectListItem>, new { @class = "form-control", @required = "required" })

                    </div>
                    <div class="form-group">
                        <label for="">Product Name</label>
                        @Html.DropDownListFor(m => m.ProductName, ViewData["productTables"] as IEnumerable<SelectListItem>, new { @class = "form-control", @required = "required" })

                    </div>
                    <div class="form-group">
                        <label for="">Offer Percent</label>
                        <input type="text" name="OfferPercent" class="form-control  mt-1" id="offerpercent" placeholder="Enter Offer Percent">
                    </div>
                    <div class="form-group">
                        <label for="">Detail</label>
                        <input type="text" name="Detail" class="form-control  mt-1" id="detail" placeholder="Enter Detail of Discount">
                    </div>
                    <br />

                    <button type="submit" class="btn btn-warning ml-2" value="Submit">Submit</button>

                </div>

              
            </div>

            }
        </div>
        <!-- /.card-body -->
    </div>

</div>

ResturantSystem/Views/Discount/Index.cshtml
@model List<ResturantSystem.Models.DiscountTable>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    int sn = 0;
}

<style>
    .background {
        background-color: white;
    }

    .btn {
        font-weight: 500;
        color: white;
    }

    .card-title {
        font-size: 20px;
        color: white;
    }
</style>

<div class="background">


    <div class="text-right">
        <a href="@Url.Action("AddDiscount","Discount")" type="button" class="btn btn-warning mt-2 mr-3"> +  Add Discount</a>
    </div>

    <!-- /.row -->
    <div class="row">
        <div class="col-12">
            <div class="card mt-2 card-warning">
                <div class="card-header">
                    <h4 class="card-title  ">Discount List</h4>

                    <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">

                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">

                        <tr>
                            <th>SN</th>
                            <th>FoodCategory</th>
                            <th>ProductName</th>
                            <th>OfferPercent</th>
                            <th>Detail</th>
                            <th>Action</th>

                        </tr>

                        @foreach (var data in Model)
                        {
                    <tr>
                        <td>@(++sn)</td>
                        <td>@(data.FoodCategory)  </td>
                        <td>@(data.ProductName)  </td>
                        <td>@(data.OfferPercent)  </td>
                        <td>@(data.Detail)  </td>
                        <td>
                            <a href="@Url.Action("EditDiscount", new {Id=data.Id})"><span class="fas fa-pencil"></span></a>
                            <a type="button" data-bs-toggle="modal" data-bs-target="#exampleModal_@data.Id"><span class="fas fa-trash ml-3 text-red"></span></a>
                        </td>
                        <div class="modal fade" id="exampleModal_@data.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        Do you want to Delete ?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                        <a type="button" href="@Url.Action("DeleteDiscountData","Discount", new {Id=data.Id})" class="btn btn-danger">Confirm</a>
                                    </div>
                                </div>
                            </div>
                        </div>


                    </tr>
                        }
                    </table>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>

</div>